/*
 * File: DefaultErrorHandler.java
 * 
 * Copyright 2012 OSFramework Project.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.osframework.contract.date.fincal.config.xml;

import org.slf4j.Logger;
import org.xml.sax.ErrorHandler;
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;

/**
 * Default base implementation of SAX <code>ErrorHandler</code>. This class
 * provides simple logging of errors generated by <code>Validator</code> and
 * parser objects.
 *
 * @author <a href="mailto:dave@osframework.org">Dave Joyce</a>
 */
public class DefaultErrorHandler implements ErrorHandler {

	private final Logger logger;

	public DefaultErrorHandler(Logger logger) {
		this.logger = logger;
	}

	@Override
	public void warning(SAXParseException exception) throws SAXException {
		logger.warn(exception.getMessage());
	}

	@Override
	public void error(SAXParseException exception) throws SAXException {
		logger.error("Parser Error: {}", exception.getMessage());
	}

	@Override
	public void fatalError(SAXParseException exception) throws SAXException {
		logger.error("**Parser Fatal Error**", exception);
		throw exception;
	}
	
}